### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by Azzazelllo** [nesrual/fail2ban-cloudflare#3]
# /usr/bin/ruby /etc/fail2ban/cloudflare_api_manager.rb unban 1.1.1.1
Error:
/etc/fail2ban/cloudflare_api_manager.rb:83:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by nesrual** [comment]
Thanks. I will look into it.

**Comment by HoverCatz** [comment]
Really, still no fix? :(

**Comment by MachiavelSST** [comment]
> 
> 
> Really, still no fix? :(

Hello,
I made some changes, check the pull requests.
